# eslint-disable pnpm/yaml-no-duplicate-catalog-item

catalogMode: prefer

shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: warn

packages:
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^7.7.3
    '@oiij/tsconfig': ^0.0.1
    '@oiij/unocss-preset': ^0.0.1
    '@tsdown/css': ^0.21.4
    '@types/node': ^25.5.0
    '@types/three': ^0.183.1
    '@vitest/ui': ^4.1.0
    bumpp: ^11.0.1
    colord: ^2.9.3
    commitlint: ^20.5.0
    cz-git: ^1.12.0
    czg: ^1.12.0
    eslint: ^10.0.3
    eslint-plugin-format: ^2.0.1
    esno: ^4.8.0
    jsonfile: ^6.2.0
    lint-staged: ^16.4.0
    naive-ui: ^2.44.1
    postcss: ^8.5.8
    rolldown-plugin-unocss: ^0.1.0
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    three: ^0.183.2
    tsdown: ^0.21.4
    typescript: ^5.9.3
    unocss: ^66.6.7
    unplugin-vue: ^7.1.1
    vitepress: ^1.6.4
    vitepress-demo-plugin: ^1.5.1
    vitest: ^4.1.0
    vue: ^3.5.30
    vue-tsc: ^3.2.6
  pkg:
    '@css-render/plugin-bem': ^0.15.14
    '@css-render/vue3-ssr': ^0.15.14
    '@emoji-mart/data': ^1.2.1
    '@splinetool/runtime': ^1.12.69
    '@tiptap/core': ^3.20.4
    '@tiptap/extension-image': ^3.20.4
    '@tiptap/pm': ^3.20.4
    '@tiptap/starter-kit': ^3.20.4
    '@tweakpane/core': ^2.0.5
    '@tweakpane/plugin-essentials': ^0.2.1
    '@tweenjs/tween.js': ^25.0.0
    '@types/file-saver': ^2.0.7
    '@types/markdown-it': ^14.1.2
    '@types/prismjs': ^1.26.6
    '@types/three': ^0.183.1
    '@visactor/vchart': ^2.0.19
    '@vueuse/core': ^14.2.1
    aieditor: ^1.4.2
    async-validator: ^4.2.5
    cannon-es: ^0.20.0
    colord: ^2.9.3
    css-render: ^0.15.14
    dompurify: ^3.3.3
    echarts: ^6.0.0
    emoji-mart: ^5.6.0
    es-toolkit: ^1.45.1
    file-saver: ^2.0.5
    hucre: ^0.3.0
    jspdf: ^4.2.1
    jszip: ^3.10.1
    markdown-it: ^14.1.1
    naive-ui: ^2.44.1
    nanoid: ^5.1.7
    ogl: ^1.0.11
    pdfjs-dist: ^5.5.207
    postprocessing: ^6.38.3
    prismjs: ^1.30.0
    shiki: ^4.0.2
    three: ^0.183.2
    tweakpane: ^4.0.5
    vue: ^3.5.30
    vue-component-type-helpers: ^3.2.6
    vue-hooks-plus: ^2.4.3
    vue-i18n: ^11.3.0
    vue-router: ^5.0.3
    xlsx: ^0.18.5
